hitcount_project/urls.py
from django.contrib import admin
from django.urls import path,include
from . import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("home.urls")),
    path('ratings/', include('star_ratings.urls', namespace='ratings')),
    path('comment/', include('comment.urls')),
]+ static(settings.MEDIA_URL , document_root = settings.MEDIA_ROOT)

home/urls.py
from django.urls import path,re_path,include
from .import views

app_name="home"

urlpatterns=[
    path('',views.home,name='home'),
    re_path(r'article/detail/(?P<slug>[-\w]+)',views.ArticleView.as_view(),name="article-detail"),
    path('hitcount/', include(('hitcount.urls', 'hitcount'), namespace='hitcount')),
    path("create",views.ArticleCreate.as_view(),name="article-create"),

]

home/models.py
from django.db import models
from django.urls import reverse
from hitcount.models import HitCountMixin, HitCount
from django.contrib.contenttypes.fields import GenericRelation
from star_ratings.models import Rating
from comment.models import Comment
class Article(models.Model):
    title = models.CharField(max_length=30,verbose_name="عنوان")
    description = models.TextField(verbose_name="توضیحات")
    image=models.ImageField(upload_to='Image',verbose_name="تصویر ")
    slug = models.SlugField(unique=True,verbose_name="آدرس",allow_unicode=True)
    hit_count_generic = GenericRelation(HitCount, object_id_field='object_pk',related_query_name='hit_count_generic_relation')
    ratings = GenericRelation(Rating, related_query_name='foos')
    # date = models.DateTimeField()
    comments=GenericRelation(Comment)
    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('home:article-detail' , args=[self.slug])



   

home/views.py
from django.shortcuts import render
from.models import Article
from hitcount.views import HitCountDetailView
from django.views.generic import CreateView
from django.urls import reverse_lazy
from django.utils.text import slugify
def home(request):
    #popular_posts=Article.objects.filter(ratings__isnull=False).order_by('-ratings__average')  #based on average of ratings
    popular_posts=Article.objects.order_by('-hit_count_generic__hits') #based on hit-count
    # recent_posts= Article.objects.order_by('-date')[:6] #based on date of upload
    return render(request,"home/home.html",{'popular_posts':popular_posts })

class ArticleView(HitCountDetailView):
    model = Article
    template_name = 'home/article-detail.html'
    context_object_name = 'article'
    slug_field = 'slug'
    # set to True to count the hit
    count_hit = True    

class ArticleCreate(CreateView):
    model=Article
    fields=['title','description','image']
    template_name="home/article-create.html"
    success_url=reverse_lazy("home:home")
    def form_valid(self,form):
        self.obj=form.save(commit=False)
        self.obj.slug=slugify(self.obj.title,allow_unicode=True)
        return super().form_valid(form)

home/templates/home/article-create.html
{% load static %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">

    <title>ساخت مقاله</title>
</head>
<body>
    <div class="col-md-12">
        <div class="card card-primary">
            <div class="card-header">
                <h3 class="card-title mb-0 float-left">افزودن ویدئو</h3>
            </div>
            <div class="card-body">
                <form method="post" enctype="multipart/form-data">{% csrf_token %}
                    <div class="row">
                        <div class="col-6">
                            {{ form.title|as_crispy_field }}
                        </div>
                        <div class="col-12">
                            {{ form.description|as_crispy_field }}
                        </div>
                        <div class="col-6">
                            {{ form.image|as_crispy_field }}
                        </div>
                    <input class="btn btn-success" type="submit" value="ارسال آموزش"> 
                </form>
            </div>
    </div>
</body>
</html>

home/templates/home/article-detail.html
{% load hitcount_tags %}
{% load comment_tags %}  
{% include_bootstrap %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <title>Home Page</title>
</head>
<body dir="rtl" style="right:500px;position: relative;background-color: rgb(29, 103, 133);top: 50px;">
  <div class="card" style="width: 50rem;background-color: rgb(230, 255, 1);">
      <img src="{{article.image.url}}" class="card-img-top" alt="...">
      <div class="card-body">
        <h5 class="card-title" style="font-size: 50px;color: rgb(0, 225, 255);">{{article.title}}</h5>
        <p class="card-text" style="font-size: 40px;color: rgb(238, 255, 0);">{{article.description}}</p>
          <p class="card-text" style="font-size: 30px;color: rgb(255, 123, 0);">{% get_hit_count for article %} آمار بازدید</p>
      </div>
      {% render_comments article request %}  
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
</body>

</html>

home/templates/home/home.html
{% load hitcount_tags %}
{% load static %}
{% load ratings %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'star-ratings/css/star-ratings.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <title>Home Page</title>
</head>
<body dir="rtl" style="background-color: dodgerblue;">
  <div class="card-group">
  {% for article in popular_posts %}
    <div class="card mb-3" style="width:18rem;position: relative;margin: 10px;">
        <img src="{{article.image.url}}" class="card-img-top" alt="...">
        <div class="card-body">
          <h5 class="card-title">{{article.title}}</h5>
          <p class="card-text">{{article.description}}</p>
            <p class="card-text" style="font-size: 30px;color: rgb(255, 0, 0);">{% get_hit_count for article %} آمار بازدید</p>
            <p class="card-text" style="font-size: 30px;color: rgb(255, 0, 0);">{{article.comments.all.count}} نظر</p>
            {% ratings article %}
          <a href="{{article.get_absolute_url}}" class="btn btn-primary">رفتن به مقاله</a>
        </div>
    </div>
  {% endfor %}
  </div>
  <br>
  <button><a href="{% url 'home:article-create' %}"> ساخت مقاله</a></button>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
    <script type="text/javascript" src="{% static 'star-ratings/js/dist/star-ratings.min.js' %}"></script>
</body>

</html>